// Auto-generated by state-agent
// Form state for Contact
// Reasoning: Form component with onSubmit — "When" conditions for submission and validation states.

import { z, createStore } from 'state-agent'

// ─── Schema ──────────────────────────────────────────────────

export const contactFormSchema = z.object({
  name: z.string(),
  email: z.string(),
  message: z.string(),
  isSubmitting: z.boolean(),
  submitted: z.boolean(),
  error: z.string().nullable(),
  errors: z.record(z.string(), z.string()),
})

export type ContactFormState = z.infer<typeof contactFormSchema>

// ─── Store ───────────────────────────────────────────────────

export const contactFormStore = createStore<ContactFormState>({
  name: 'contactForm',
  stateSchema: contactFormSchema,
  initial: {
    name: '',
    email: '',
    message: '',
    isSubmitting: false,
    submitted: false,
    error: null,
    errors: {},
  },
  when: {
    isSubmitting: (state) => state.isSubmitting === true,
    hasErrors: (state) => Object.keys(state.errors).length > 0,
    isValid: (state) => Object.keys(state.errors).length === 0,
  },
  validate: {
    'name': (value) => value !== '',
    'email': (value) => value !== '',
    'message': (value) => value !== '',
  },
})
