// Auto-generated by state-agent
// Reasoning: App has 4 routes — navigation modeled as a flow state machine.

import { createFlow } from 'state-agent'

export const navigationFlow = createFlow({
  name: 'navigation',
  states: ['Home', 'About', 'Contact', 'Dashboard'],
  initial: 'Home',
})
