// Auto-generated by state-agent
// Wraps the app with all state providers

import React from 'react'
import { StoreProvider } from 'state-agent/react'
import { authStore } from './auth.store.js'
import { postsStore } from './posts.store.js'
import { todosStore } from './todos.store.js'
import { contactFormStore } from './contactForm.store.js'
import { sharedIsLoadingStore } from './sharedIsLoading.store.js'
import { navigationFlow } from './navigation.flow.js'

export function StateProviders({ children }: { children: React.ReactNode }) {
  return (
      <StoreProvider store={authStore}>
      <StoreProvider store={postsStore}>
      <StoreProvider store={todosStore}>
      <StoreProvider store={contactFormStore}>
      <StoreProvider store={sharedIsLoadingStore}>
        {children}
      </StoreProvider>
      </StoreProvider>
      </StoreProvider>
      </StoreProvider>
      </StoreProvider>
  )
}
