// Auto-generated by state-agent
// UI state for Notifications, Dashboard, Home
// Reasoning: These 3 components share state — grouped "Together".

import { z, createStore } from 'state-agent'

// ─── Schema ──────────────────────────────────────────────────

export const sharedIsLoadingSchema = z.object({
  notifications: z.array(z.any()),
  isLoading: z.boolean(),
  tasks: z.array(z.any()),
  filter: z.enum(['all', 'active', 'done']),
  posts: z.array(z.any()),
  error: z.string().nullable(),
})

export type SharedIsLoadingState = z.infer<typeof sharedIsLoadingSchema>

// ─── Store ───────────────────────────────────────────────────

export const sharedIsLoadingStore = createStore<SharedIsLoadingState>({
  name: 'sharedIsLoading',
  stateSchema: sharedIsLoadingSchema,
  initial: {
    notifications: [],
    isLoading: true,
    tasks: [],
    filter: 'all',
    posts: [],
    error: null,
  },
  when: {
    hasNotifications: (state) => state.notifications.length > 0,
    isEmptyNotifications: (state) => state.notifications.length === 0,
    isLoading: (state) => state.isLoading === true,
    hasTasks: (state) => state.tasks.length > 0,
    isEmptyTasks: (state) => state.tasks.length === 0,
    hasPosts: (state) => state.posts.length > 0,
    isEmptyPosts: (state) => state.posts.length === 0,
    hasError: (state) => state.error !== null,
  },
})
