// Auto-generated by state-agent
// Authentication state
// Reasoning: Auth state is separate — it gates the entire app but changes independently.

import { z, createStore } from 'state-agent'

// ─── Schema ──────────────────────────────────────────────────

export const authSchema = z.object({
  user: z.object({
    id: z.string(),
    name: z.string(),
    email: z.string().email(),
  }).nullable(),
  isAuthenticated: z.boolean(),
  isLoading: z.boolean(),
})

export type AuthState = z.infer<typeof authSchema>

// ─── Store ───────────────────────────────────────────────────

export const authStore = createStore<AuthState>({
  name: 'auth',
  stateSchema: authSchema,
  initial: {
    user: null,
    isAuthenticated: false,
    isLoading: true,
  },
  when: {
    isLoading: (state) => state.isLoading === true,
  },
  gates: {
    isAuthenticated: (state) => state.isAuthenticated === true,
    isGuest: (state) => state.user === null,
  },
})
