// Auto-generated by state-agent
// State for Dashboard
// Reasoning: Components Dashboard consume this state together — consumption-based grouping.

import { z, createStore } from 'state-agent'

// ─── Schema ──────────────────────────────────────────────────

export const dashboardSchema = z.object({
  tasks: z.array(z.any()),
  filter: z.enum(['all', 'active', 'done']),
})

export type DashboardState = z.infer<typeof dashboardSchema>

// ─── Store ───────────────────────────────────────────────────

export const dashboardStore = createStore<DashboardState>({
  name: 'dashboard',
  stateSchema: dashboardSchema,
  initial: {
    tasks: [],
    filter: 'all',
  },
  when: {
    hasTasks: (state) => state.tasks.length > 0,
  },
  gates: {
    isEmptyTasks: (state) => state.tasks.length === 0,
  },
})
