// Auto-generated by state-agent
// Server state for /todos
// Reasoning: API data + loading + error move together — "Together" principle from Views DataProvider.

import { z, createStore } from 'state-agent'

// ─── Schema ──────────────────────────────────────────────────

export const todosSchema = z.object({
  data: z.any().nullable(),
  isLoading: z.boolean(),
  error: z.instanceof(Error).nullable(),
})

export type TodosState = z.infer<typeof todosSchema>

// ─── Store ───────────────────────────────────────────────────

export const todosStore = createStore<TodosState>({
  name: 'todos',
  stateSchema: todosSchema,
  initial: {
    data: null,
    isLoading: false,
    error: null,
  },
  when: {
    isLoading: (state) => state.isLoading === true,
    hasError: (state) => state.error !== null,
  },
  gates: {
    hasData: (state) => state.data !== null,
    isEmpty: (state) => state.data === null || (Array.isArray(state.data) && state.data.length === 0),
  },
})
